import React from "react";
import Head from "next/head";
import ProductDetail from "../../../../components/ProductDetail";

export default function productDetail({ productDetail }) {
  console.log(productDetail);
  return (
    <div>
      <Head>
        <title>
          {productDetail.Result.PageTitle
            ? productDetail.Result.PageTitle
            : "Vestel'le Olur Neden Olmasın | Vestel"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductDetail productDetail={productDetail} />
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const res = await fetch(
    `https://store.vrunibex.com/mobile2/mbProduct/ProductDetail?productId=${context.params.id}`
  );
  const productDetail = await res.json();
  return {
    props: {
      productDetail,
    },
  };
};
