import React from "react";
import Head from "next/head";

export default function productDetail({ productDetail }) {
  console.log(productDetail);
  return (
    <div>
      <Head>
        <title>Product Detail | Vestel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h6>Product Detail</h6>
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const res = await fetch(
    `https://store.vrunibex.com/mobile2/mbProduct/ProductDetail?productId=${context.params.id}`
  );
  const productDetail = await res.json();
  return {
    props: {
      productDetail,
    },
  };
};
