import React from "react";
import Head from "next/head";

export default function productDetail() {
  return (
    <div>
      <Head>
        <title>Product Detail | Vestel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h6>Product Detail</h6>
      </main>
    </div>
  );
}
