import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vestel'le Olur Neden Olmasın | Vestel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button className="btn btn-primary">Deneme</button>
        <i className="fa-solid fa-angles-right"></i>
      </main>
    </div>
  );
}
