import Head from "next/head";
import CategoryCard from "../components/CategoryCard";

export default function Home({ category }) {
  console.log(category);
  return (
    <div>
      <Head>
        <title>Vestel'le Olur Neden Olmasın | Vestel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div className="row">
            {category.Result.TreeList.map(
              (item, key) =>
                item.ID < 11 && <CategoryCard key={key} item={item} />
            )}
          </div>
        </div>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    "https://store.vrunibex.com/mobile2/mbProduct/CategoryList"
  );
  const category = await res.json();
  return {
    props: {
      category,
    },
  };
};
