import React from "react";
import Head from "next/head";
import ProductCard from "../../../components/ProductCard";

export default function Products({ products }) {
  console.log(products);
  return (
    <div>
      <Head>
        <title>{products.Result.Category.PageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container my-5">
          <div className="row">
            {products.Result.ProductList.map((item, key) => (
              <ProductCard key={key} item={item} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const res = await fetch(
    `https://store.vrunibex.com/mobile2/mbProduct/ProductList?CategoryID=${context.params.id}`
  );
  const products = await res.json();
  return {
    props: {
      products,
    },
  };
};
