import React from "react";
import Head from "next/head";

export default function Products({ products }) {
  console.log(products);
  return (
    <div>
      <Head>
        <title>Vestel'le Olur Neden Olmasın | Vestel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h5>Products</h5>
      </main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const res = await fetch(
    `https://store.vrunibex.com/mobile2/mbProduct/ProductList?CategoryID=${context.params.id}`
  );
  const products = await res.json();
  return {
    props: {
      products,
    },
  };
};
